# Generated by Django 5.0.7 on 2024-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookah',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
