# Generated by Django 5.0.7 on 2024-07-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0003_hookah_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='cocktail',
            new_name='hookah',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('hookah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookahs.hookah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hookah',
            name='my_cart',
            field=models.ManyToManyField(related_name='my_cart', through='hookahs.Cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
