# Generated by Django 5.0.7 on 2024-07-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0007_cart_booking_date_cart_booking_time_cart_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
