# Generated by Django 5.0.7 on 2024-07-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0008_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='tobacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hookahs.tobacco'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tobacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hookahs.tobacco'),
        ),
        migrations.AddField(
            model_name='order',
            name='tobacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hookahs.tobacco'),
        ),
    ]
