# Generated by Django 5.0.7 on 2024-07-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0009_tobacco_cart_tobacco_favorite_tobacco_order_tobacco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='tobacco',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tobacco',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tobacco',
        ),
        migrations.AddField(
            model_name='hookah',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hookahs.category'),
        ),
        migrations.DeleteModel(
            name='Tobacco',
        ),
    ]
