# Generated by Django 5.0.7 on 2024-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0010_category_remove_favorite_tobacco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hookah',
            name='flavors',
            field=models.ManyToManyField(blank=True, null=True, to='hookahs.flavor'),
        ),
    ]
