# Generated by Django 5.0.7 on 2024-07-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0011_flavor_hookah_flavors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hookah',
            name='flavors',
        ),
        migrations.AddField(
            model_name='hookah',
            name='flavors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hookahs.flavor'),
        ),
    ]
