# Generated by Django 5.0.7 on 2024-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookahs', '0012_remove_hookah_flavors_hookah_flavors'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hookah_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
